name: GitHub Car Accessories Project

on:
  push:
    branches: [main]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Step1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step2 - Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Step3 - Build Maven Project
        run: mvn --batch-mode -DskipTests package

      - name: Step4 - run test cases
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
